### ISSUE TITLE
Add branches-ignore to merge_group schema

### ISSUE THREAD

**Issue by lrotschy** [actions/languageservices#18]
See comment on previous PR: https://github.com/actions/languageservices/pull/12#issuecomment-1500715535

Investigate adding branches-ignore to merge_group schema.

**Comment by muzimuzhi** [comment]
Just to re-confirm before I report similar issues to [`github/docs`](https://github.com/github/docs) and [`rhysd/actionlint`](https://github.com/rhysd/actionlint), does this mean `on.merge_group.branches-ignore` is officially supported by GitHub Actions in public beta?
